name: Build and Publish package
on:
  push:
    branches: [ githubreleaseworkflow ]
  workflow_dispatch:

jobs:
  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Scan
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/trivy_scan.sh && chmod +x trivy_scan.sh
          ./trivy_scan.sh
          rm trivy_scan.sh
  build-publish-package:
    name: Build and Publish package
    runs-on: macos-11
    needs: Trivy
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install compass
        run: |
          sudo gem install compass -v 1.0.3
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean -U package -DskipTests
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false

      - name: Upload SNAPSHOT.omod to release
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./target/bahmnicore-omod-VERSION-SNAPSHOT.omod
            asset_name: bahmnicore-omod-VERSION-SNAPSHOT.omodd
            asset_content_type: application/octet-stream
